CREATE OR ALTER PROCEDURE SP_DeleteSpec 
    @SpecId INT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM Specs 
    WHERE SpecID = @SpecId
      AND NOT EXISTS(SELECT 1 FROM Devices WHERE SpecID = @SpecId);

        SELECT @@ROWCOUNT; 
END
